### ISSUE TITLE
Support dynamic (extendable) schemas

### ISSUE THREAD

**Issue by pmos69** [vast-io/vast#107]
To enable input of data from sources where all possible fields are not documented/known in advance. (add field to existing schema).
And, if possible, the input of data that doesn't have all the fields already present in the schema. (default null value for missing fields in input).

**Comment by pmos69** [comment]
Doesn't make sense.
Vast already has dynamic schemas:
  - new fields in input generate a new schema
  - less fields in input generate a new schema
  - different types for existing fields in new input generate a new schema

Only support for order agnostic input is missing, but that is open in #78 
...and possibly "automagic" type inference, but that would also need support a new import format, since bro format is typed (JSON?)

**Comment by pmos69** [comment]
Crap. No it doesn't. (Was load balancing between partitions)

**Comment by mavam** [comment]
In the current model, a given type can always have one schema. (I'm using the word "schema" now as "layout"). I'm also assuming that a type can evolve over time, but there will always be one current type. That is, a type can have a temporal history. What this model cannot capture is a single type (identified by its name) with multiple schemata.

Do these semantics work for your use cases?

**Comment by pmos69** [comment]
Sure. That's clear.
What I still don't understand is how a schema can evolve over time. If you already have a schema present for a given type, Vast will not allow you to import data with a new schema.
Is there an API for schema manipulation? I've only seen Vast creating schemas by importing data of a new type.

**Comment by mavam** [comment]
> What I still don't understand is how a schema can evolve over time. If you already have a schema present for a given type, Vast will not allow you to import data with a new schema.

Right. Currently that's the case, but I would like to move towards a notion where import succeeds in the presence of multiple conflicting types.

> Is there an API for schema manipulation? I've only seen Vast creating schemas by importing data of a new type, except when the partition load balancing enabled a different schema for the same type to be created in a different partition, but that's just a side effect.

Correct. At this point the format-specific sources determine the schema automatically. It's already possible to provide a schema as extra command line parameter, via `-s <schema>`. This requires that `schema` has a definition of a type which is *congruent* to the inferred type, that is, representationally equal. For example, after making records order-agnostic, two records with the same field names and same types, but different field order, would be representationally equal. Also, types which only differ in their attributes have a different signature, but are otherwise representationally equal.

> Adding, dropping or changing the type of a field in a schema can seem pretty straightforward to me, but that is surely because of my limited knowledge of all the factors involved, as it would seem to me to only involve creating or dropping specific indexes (says me, the expert).

Right now, you can already control the creation of indexes by providing a schema with types congruent to those in the import data. You just need to add the `&skip` attribute. It's really not user-friendly, and in the future, VAST will offer an API where you can add/drop indexes.

> For a given type, making schemas "order agnostic" at the time of import of new data (not as a schema change for existing data) is a much simpler case, as it should just be a matter of comparing the current schema with the schema of data being imported to check if the same fields are present and shuffling the order of the the data being imported to conform with the current schema.

Yes. The way I'll implement this by using a `std::map` internally, as opposed to a `std::vector`. In fact, I would like to create a more cache and allocator friendly  `flat_map` data structure, analogous to the existing `util::flat_set`. This needs to happen for both types and data. In addition to that change, we need to convert the candidate checkers, which are visitors invoked over the raw events after an index hit to ensure that the hit is actually a result. This is not always the case, e.g., because floating-point and time indexes are rounded off by default. These currently use a numeric index to get to recursive elements. For example, a visitor which checks for `*.x.z` with a record type `{ x: int, r: record { y: int, z: int } }`, uses the index sequence `[1,0]` to first go `r`, and then to `z`. This is faster than looking up `r` and `z` by name, but requires a random-access data structure. Anyway, that's just a low-level implementation detail.

> Importing data with a subset of the fields in the current schema should even be easier to implement, simply by having the missing fields in the imported data filled with nil.

Hm, this would violate strong type safety. What would be the Bro use case for that? To define one big type with, say, a bunch of extra conn.log fields, and then set them to `nil` if they don't show up?

I think we can work this out, though, by defining the notion of strict superset/subset relationship between types, and then flip a switch during import that either toggles strict type safety checks, or also accepts a subset of the known type.

**Comment by pmos69** [comment]
> Hm, this would violate strong type safety. What would be the Bro use case for that? To define one big type with, say, a bunch of extra conn.log fields, and then set them to nil if they don't show up?

Not BRO data, but data in **BRO format** :)
Remember that in practical terms, at this time BRO is the only source/importer that can be used at this time to import data from other sources. I've built a few parsers for other data sources that convert their native formats to BRO format and use those in testing:
**streaming source** ----(native format)----> **Parser** ----(BRO format)----> **Vast**

(Yes, JSON would be 1000% better, but I know you're busy. Hint: #63).

There are native formats that are variants of key-value formats that include in each record only the key-value pairs for which they have values in that event.
Some native formats are well documented, while others very poorly, with not even all the possible keys documented.

For well documented sources, the parsers send all the possible fields to Vast, even if they aren't present in the input data, and in a predefined order, because that is the only way to always conform with the schema. Fields not present in the input data are sent empty, but still have to be sent.
For sparse data, which a lot of these end up being, a much larger volume of information than needed to be sent is then processed.

Poorly documented sources suffer more from Vast not being able to dynamically add fields to existing schemas, although they also raise other issues.
