### ISSUE TITLE
&type is logged as an unsupported attribute

### ISSUE THREAD

**Issue by josephnoir** [vast-io/vast#138]
When executing a query that includes a type such as `vast export bro "&type == \"bro::bgpupdates\" && :count == 12"`, the query does not return anything and the main node logs the following:

```
partition got expression: {&type == "bro::bgpupdates" && :count == 395536}
event-indexer got predicate: &type == "bro::bgpupdates"
event-indexer got unsupported attribute: type
event-indexer did not find matching indexers for &type == "bro::bgpupdates"
```

I am bit bugged by the following statement that no *matching indexers* were found. That sounds like the type query is handled but does not match my data. Am I mistaken, that the type of a bro log is its path?

**Comment by mavam** [comment]
What's the input data you used for this query? Is there indeed a type named `bro::bgpupdates`?

**Comment by josephnoir** [comment]
I hope so, here is the head of the log:

```
$ head -n 15 ./bgplog.bro 
#separator \x09
#set_separator	,
#empty_field	(empty)
#unset_field	-
#path	bgpupdates
#open	2017-07-15-12-20-50
#fields	collector	ts	type	origin	prefix
#types	string	time	string	count	subnet
route-views.perth	1499934053.0	A	395536	50.204.196.0/24	
rrc10	1499934053.0	A	395536	50.204.196.0/24	
route-views.linx	1499934054.0	A	395536	50.204.196.0/24	
route-views.linx	1499934054.0	A	4809	59.60.0.0/20	
route-views.linx	1499934054.0	A	395536	50.204.196.0/24	
route-views.linx	1499934054.0	A	4809	59.60.0.0/20	
route-views.linx	1499934054.0	A	4809	117.28.224.0/19	
```

**Comment by mavam** [comment]
Thanks, I can reproduce the issue now.

**Comment by mavam** [comment]
Here's the problem: when a PARTITION receives the expression, it rips it apart into its predicates and sends each predicate to *all* known INDEXERs. Thankfully there are a few FIXME comments in the code that indicate how to go after the problem. What needs to happen is that we switch to a lazy loading scheme where we only load the INDEXERs needed for a particular query.

Then, we should identify the `&type` predicates and send predicates in any conjunction constrained by it only to the corresponding INDEXER. Because this is a tricky logic and requires a bit of AST walking, the existing solution is pretty lame: just broadcast all predicates to all INDEXERs.

Back to the warning `event-indexer got unsupported attribute: type`. This is correct. The INDEXER should never see a predicate with `&type`, because its parent PARTITION should have done the proper filtering and not sent the predicate to it in the first place. Therefore, the issue is technically not a correctness bug, but a performance issue.

I'll take care of it by rewriting the way a PARTITION manages its INDEXERs.

**Comment by josephnoir** [comment]
Just to clarify, the query `vast export bro "&type == \"bro::bgpupdates\" && :count == 395536"` does not only print the warning, but it doesn't seem to work either.

(Noticed that I wrote the wrong `:count` value in the query above, hence the clarification.)

**Comment by mavam** [comment]
You're right. Since the `&type` predicate still lingers in the conjunction at the PARTITION (and falsely returns with 0 hits), the other hits of the predicates in the conjunction (here: `:count == 395539`) get nixed, even though they report the correct hits.
