### ISSUE TITLE
Allow import filters to reference already imported data

### ISSUE THREAD

**Issue by josephnoir** [vast-io/vast#143]
When importing data it would be neat to reference already imported data in the filter. For example: "import only new events that have an ip address that falls into a subnet included in that column".

Could this be implemented efficiently?

Our current workaround is to export the data for the filter in a script and use it to create an import filter.

**Comment by mavam** [comment]
I'm not sure if I have understood the full picture. Is the premise that events that have been previously imported are imported again? Based on your example, it sounds like the events may not exactly be the same (e.g., varying timestamp) but a subset of them overlaps with existing data. Deduplication, essentially. Did I get this right?

More broadly, it sounds like you would like to have dynamic import filters. This is certainly something we need to revisit, because a static expression is quite limited in a continuously changing environment.

> Could this be implemented efficiently?

Any solution that would tie the import to archive and index would not perform with high data rates.

One thought that came to mind immediately in this regard is the use of Bloom filters for set membership tests. Except it's the inverse problem: we want to tolerate false negatives but not false positives. The dual to a Bloom filter is some form of (direct-mapped) cache, which often comes in the form of a hash table. That would be possible to implement efficiently, but assumes locality in the data input, which may not be the case for IP addresses all over the world. The implication would be that some data would get duplicated, but not the subset absorbed by the cache.

Another efficient approach could be pruning: first insert everything, including duplicates, and then remove redundant entries later, in a second pass. But there's currently no machinery in place for deletion. It would probably be easy to add (just another bitmap to mark deleted event IDs), but it's not immediately clear to me how to find a feasible solution to the uniqueness problem, especially for large domains like IPv6 addresses.

**Comment by josephnoir** [comment]
> I'm not sure if I have understood the full picture. Is the premise that events that have been previously imported are imported again? Based on your example, it sounds like the events may not exactly be the same (e.g., varying timestamp) but a subset of them overlaps with existing data. Deduplication, essentially. Did I get this right?

No, not exactly. Its not about importing duplicated data, but related data. For example one set of logs might include subnets while another (different) one contains ip addresses. After having imported the logs that include subnets, you might only want to import events from the second set of logs that contains IP addresses that are included in a subnet you imported previously.

> Any solution that would tie the import to archive and index would not perform with high data rates.

Yeah, that is what I am afraid of. Not sure if you could buffer data to continuously speed this up ...

>  It would probably be easy to add (just another bitmap to mark deleted event IDs), [...]

That might prevent VAST from returning deleted events, but doesn't memory management over time. (And possible data regulation laws?)

**Comment by mavam** [comment]
> For example one set of logs might include subnets while another (different) one contains ip addresses. After having imported the logs that include subnets, you might only want to import events from the second set of logs that contains IP addresses that are included in a subnet you imported previously.

Got it, so it's in fact some custom, cross-correlating logic. I'm afraid this is something that will not be easy to support in full generality (At least not at import time).

Upleveling, I wonder what generic primitives are enough to express a meaningful set of such constraints. A a separate filtering component could maintain some constant-space state (e.g., a list of mergeable subnets in a ring buffer) and then perform some computation with it. But that's pretty low-level.

> That might prevent VAST from returning deleted events, but doesn't memory management over time. > (And possible data regulation laws?)

Yeah, aging out old data is the next big thing we need to tackle for operational settings!

**Comment by josephnoir** [comment]
> Got it, so it's in fact some custom, cross-correlating logic. I'm afraid this is something that will not be easy to support in full generality (At least not at import time).

I thought so. The operations would be pretty complex and time consuming.

**Comment by mavam** [comment]
I'm closing this one for now because there's no clear path forward on creating a feature that's not a one-off.
